In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [19]:
from sklearn import datasets, naive_bayes, model_selection

In [5]:
digits = datasets.load_digits()

In [16]:
digits.data[:5]

array([[  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.,   0.,   0.,  13.,
         15.,  10.,  15.,   5.,   0.,   0.,   3.,  15.,   2.,   0.,  11.,
          8.,   0.,   0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.,   0.,
          5.,   8.,   0.,   0.,   9.,   8.,   0.,   0.,   4.,  11.,   0.,
          1.,  12.,   7.,   0.,   0.,   2.,  14.,   5.,  10.,  12.,   0.,
          0.,   0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  12.,  13.,   5.,   0.,   0.,   0.,   0.,   0.,
         11.,  16.,   9.,   0.,   0.,   0.,   0.,   3.,  15.,  16.,   6.,
          0.,   0.,   0.,   7.,  15.,  16.,  16.,   2.,   0.,   0.,   0.,
          0.,   1.,  16.,  16.,   3.,   0.,   0.,   0.,   0.,   1.,  16.,
         16.,   6.,   0.,   0.,   0.,   0.,   1.,  16.,  16.,   6.,   0.,
          0.,   0.,   0.,   0.,  11.,  16.,  10.,   0.,   0.],
       [  0.,   0.,   0.,   4.,  15.,  12.,   0.,   0.,   0.,   0.,   3.,
         16.,  15.,  14.,   0.,   0.,   0.,   0.,   8.,  13.

Признаки целые числа.

In [42]:
model_selection.cross_val_score(naive_bayes.BernoulliNB(), digits.data, digits.target).mean()

0.82582365077805819

In [43]:
model_selection.cross_val_score(naive_bayes.MultinomialNB(), digits.data, digits.target).mean()

0.87087714897350532

In [44]:
model_selection.cross_val_score(naive_bayes.GaussianNB(), digits.data, digits.target).mean()

0.81860038035501381

Так как признаки целые числа, но не только {0,1}, то неудивительно то, что наивный байес с мультиномиальным распределением показал наилучший результат. При этом на этом датасете предположение о независимости признаков оказывается не самым лучшим.

In [12]:
cancer = datasets.load_breast_cancer()

In [17]:
cancer.data[:5]

array([[  1.79900000e+01,   1.03800000e+01,   1.22800000e+02,
          1.00100000e+03,   1.18400000e-01,   2.77600000e-01,
          3.00100000e-01,   1.47100000e-01,   2.41900000e-01,
          7.87100000e-02,   1.09500000e+00,   9.05300000e-01,
          8.58900000e+00,   1.53400000e+02,   6.39900000e-03,
          4.90400000e-02,   5.37300000e-02,   1.58700000e-02,
          3.00300000e-02,   6.19300000e-03,   2.53800000e+01,
          1.73300000e+01,   1.84600000e+02,   2.01900000e+03,
          1.62200000e-01,   6.65600000e-01,   7.11900000e-01,
          2.65400000e-01,   4.60100000e-01,   1.18900000e-01],
       [  2.05700000e+01,   1.77700000e+01,   1.32900000e+02,
          1.32600000e+03,   8.47400000e-02,   7.86400000e-02,
          8.69000000e-02,   7.01700000e-02,   1.81200000e-01,
          5.66700000e-02,   5.43500000e-01,   7.33900000e-01,
          3.39800000e+00,   7.40800000e+01,   5.22500000e-03,
          1.30800000e-02,   1.86000000e-02,   1.34000000e-02,
       

Признаки вещественные числа

In [45]:
model_selection.cross_val_score(naive_bayes.BernoulliNB(), cancer.data, cancer.target).mean()

0.62742040285899936

In [46]:
model_selection.cross_val_score(naive_bayes.MultinomialNB(), cancer.data, cancer.target).mean()

0.89457904019307521

In [47]:
model_selection.cross_val_score(naive_bayes.GaussianNB(), cancer.data, cancer.target).mean()

0.9367492806089297

Так как признаки вещественные, то гауссовское распределние оказалось наилучшим.

### Вопросы:

1) Максимальное качество получилось на breast_cancer 0.94 с использованием наивного байеса с гауссовским распределением.

2) Максимальное качество получилось на digits 0.87 с использованием наивного байеса с мультиномиальным распределением.

3) Верны: (c), (d): мультиномиальное распределние лучше всего на целых неотрицательных признаках. На вещественных признаках лучше всего Гауссовское распределение.

Рассмотрим также датасет ирисы Фишера

In [32]:
iris = datasets.load_iris()

In [33]:
iris.data[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [39]:
model_selection.cross_val_score(naive_bayes.BernoulliNB(), iris.data, iris.target).mean()

0.33333333333333331

In [40]:
model_selection.cross_val_score(naive_bayes.MultinomialNB(), iris.data, iris.target).mean()

0.96078431372549022

In [41]:
model_selection.cross_val_score(naive_bayes.GaussianNB(), iris.data, iris.target).mean()

0.93423202614379086

Хотя и числа здесь вещественные, но все они представлены с точностью 1 знак после запятой, этим можно объяснить то, что наивный байес с мультиномиальным распределением оказался лучше, чем с гауссовским. 